### ISSUE TITLE
Export fails

### ISSUE THREAD

**Issue by almo2001** [DarkFenX/Pyfa#251]
When I export a ship fitting, the XML file contains this:

<?xml version="1.0" ?>
<fittings/>

And nothing else. Mac OSX 10.9.5 (latest Mavericks)

**Comment by DarkFenX** [comment]
Was fixed in 3a9e1f8b850de68bfe574b7ddb4b743a4f2194ef

**Comment by blitzmann** [comment]
As a note: many people still export to XML to import to EVE. A much easier way is to use the EFT export and import into EVE using the Import from Clipboard option. =)

I don't know whether the export fix is critical enough to warrant another release - depends on how many people report it as an issue

**Comment by almo2001** [comment]
I tried export to clipboard, and EVE said it couldn't import from clipboard. Did I do it wrong or something?

**Comment by blitzmann** [comment]
Export to EFT format, and it should work with the condition that cargo isn't included (I don't think the EVE client accepts cargo items with clipboard import, which are included in the EFT export format and something I should probably remove)

**Comment by GooseToe** [comment]
Using Windows and latest build downloaded today.  Still can't export to XML when selecting individual ships.  Complete fitting backup works.   Copy to clipboard > XML contains just 
<?xml version="1.0" ?>
<fittings/>
Same for Ctrl-S /  File > Export Fitting    Creates file with same contents.

**Comment by blitzmann** [comment]
Well, yeah, because the fix happened after the latest release (v1.8.1). It's actually the first commit after that.

It's not significant enough to make a new release, especially since EVE client takes EFT import now and with next expansion relatively close. The fix will ship with v1.9
